# Generated by Django 5.2.12 on 2026-03-28 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0004_contact_created_at_contact_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="opencrm.company",
                verbose_name="Company",
            ),
        ),
    ]
