# Generated by Django 5.2.12 on 2026-03-28 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0009_remove_company_company_type_company_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="tag",
            new_name="type",
        ),
    ]
