# Generated by Django 5.2.12 on 2026-03-28 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0010_rename_tag_company_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companytype",
            old_name="type",
            new_name="name",
        ),
    ]
