# Generated by Django 5.2.12 on 2026-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0012_alter_company_name_alter_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="contact", to="opencrm.tag"
            ),
        ),
    ]
