# Generated by Django 5.2.12 on 2026-04-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0013_alter_contact_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.TextField(),
        ),
    ]
