# Generated by Django 5.2.12 on 2026-04-05 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opencrm", "0014_alter_note_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="opencrm.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="opencrm.contact",
            ),
        ),
    ]
